services:
  - type: web
    name: alzheimermm-dashboard
    env: python
    region: virginia
    plan: free
    rootDir: dashboard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.17
      - key: RENDER
        value: true